[package]
name = "lavish-browser-cli"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
lavish-browser-control = { path = "../control" }
lavish-browser-core = { path = "../core" }
lavish-browser-protocol = { path = "../protocol" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[[bin]]
name = "lavish-open"
path = "src/bin/lavish-open.rs"

[[bin]]
name = "lavish-browser-ctl"
path = "src/bin/lavish-browser-ctl.rs"
